### ISSUE TITLE
Cannot export complex types 

### ISSUE THREAD

**Issue by maxxer** [mohorev/yii2-soap-server#2]
First of all thank you very much for your work.

I'm trying to return an Yii2 model in a SOAP call. Following the 1.1 guide I added the `classMap` option to the `actions` method in the controller, then in the model I added custom `@var` for the attributes I'd like to export like stated in the [1.1 doc](http://www.yiiframework.com/doc/guide/1.1/it/topics.webservice):

```
class MyModel extends \yii\db\ActiveRecord {
/** 
 * @var string 
 * @soap 
 */
public $title;

[...]
```

But differently from Yii1, the local property overrides model's one, which then returns an empty property! 
I'm not sure this is your library bug... but did you ever run into a similar situation? Is there a different specification for exporting model's properties?

**Comment by maxxer** [comment]
This is an excerpt of my controller:

```
public function actions()
{
    return [
        'index'=> [
            'class'=>'mongosoft\soapserver\Action',
            'classMap' => [
                'MyModel' => 'MyModel',
            ],
        ],
    ];
}

/**
 * @return app\models\MyModel
 * @soap
 */
public function getMyModel () 
{
    $var = MyModel::findOne(1);
    return $var;
}
```

**Comment by mohorev** [comment]
ActiveRecord can not load the value of the property in the associated public property of your class. 
You need to do it yourself. ActiveRecord in Yii2 is very different from the Yii1. All fields of the database and their values are stored in a protected property $ _attributes and invoked via magic methods.

**Comment by maxxer** [comment]
something like this:

```
public function afterFind() {
    parent::afterFind();
    $this->title = parent::__get('title');
}
```

**Comment by mohorev** [comment]
Something like this:

``` php
public function afterFind()
{
    parent::afterFind();
    $this->title = $this->getAttribute('title');
}
```

or create wrapper object

``` php
class MyModel extends yii\base\Model
{
    /**
     * @var string
     */
    public $title;
}
```

``` php
/**
 * @return app\models\MyModel
 * @soap
 */
public function getMyModel() 
{
    $var = Article::findOne(1);

    return new MyModel([
        'title' => $var->title,
    ]);
}


```

**Comment by maxxer** [comment]
I solved this way:

```
public function afterFind() {
    parent::afterFind();

    $ref = new ReflectionClass($this->className()); 
    foreach ($ref->getProperties() as $prop) {
        if ($prop->getReflectionDocComment()->getAnnotationsCollection()->hasAnnotationTag('soap')) {
            $propname = $prop->getName();
            $this->$propname = $this->getAttribute($propname);
        }
    }
}
```

This could probably fit into a `behaviour`

**Comment by maxxer** [comment]
I uploaded my behavior [here](https://gist.github.com/maxxer/219e8147eb4647ac2a44).
Do you want me to create a PR to ease soap usage?

**Comment by philippfrenzel** [comment]
I would like to See it merged;)

**Comment by maxxer** [comment]
Just for the record the method above doesn't work 100%. It works for SOAP, but breaks the `$model->_attributes` array generation so on `->insert` only the non re-declared attributes are saved!  

To work around it I named my exportable attributes like `public $SOAPattrname` and in the behavior 

``` diff
-                $this->owner->$propname = $this->owner->getAttribute($propname);
+                $model_attr = preg_replace('/^SOAP/', '', $propname);
+                $this->owner->$propname = $this->owner->getAttribute($model_attr);
```
