### ISSUE TITLE
Option to disable WSDL mode

### ISSUE THREAD

**Issue by michaelarnauts** [mohorev/yii2-soap-server#4]
It would be useful if there was an option to disable the WSDL-mode of the SoapServer.

This can solve two problems:
- When we use an authenticator (with HttpBasicAuth for example) to secure the service, the SoapServer can't download the WSDL itself since it doesn't provide the required authentication.
- When we use the SoapServer to handle complex requests (with a WSDL that doesn't fit in the @param-options), SoapServer will always complain that the parameters are incorrect. Disabling the WSDL-mode and handling the XML of the request manually solves this issue.

**Comment by michaelarnauts** [comment]
See pull request #5

**Comment by mohorev** [comment]
Thanks.
